Added changes to Terraform Equinix Modules docs to include versioning, pr's, and commits
equinix-labs/equinix-labs pull request #103
Opened 2023-03-22 06:02 UTC by dcallao

This PR contains the following changes:
- hyperlink format changes
- markdown lint throughout the doc
- added info in section 5. and 6. of the `Using the Terraform Equinix Modules Template` section

2023-03-22 17:11 UTC, ctreatma requested changes
Looks good to me overall, just spotted one broken link to the template

2023-03-29 22:15 UTC, dcallao commented on terraform-modules.md
> +Terraform modules should either be sourced from [Template module template] or closely following the format of this project.
The link to the template is defined right at the bottom of the page [here](https://github.com/equinix-labs/equinix-labs/pull/103/files#diff-1fc1b42aafd40dda0e7b140e3d8a0e5f9b41e024cc0dbc87bbf0aa9ad060dd3cR119). 👍

2023-03-29 22:56 UTC, dcallao commented
@ctreatma I have updated the Terraform md doc slightly to include the CI jobs that will run once a PR is submitted and the CI jobs that will run when the PR is approved and merged.

2023-04-18 21:23 UTC, ctreatma approved these changes

2023-04-18 21:33 UTC, dcallao commented on terraform-modules.md
> +3. <a name="jointeam"></a> Join the [Equinis-labs Terraform team]
Thanks! Fixed via [7a26422](https://github.com/equinix-labs/equinix-labs/commit/7a2642225e9769cd3bec0a61e28ff14d4b1bf1de)

2023-04-19 01:35 UTC, displague approved these changes

2023-04-28 17:08 UTC, merged